### ISSUE TITLE
Mod requirement Missing

### ISSUE THREAD

**Issue by Zhaulus** [CraftmoreMC/Alchemist#2]
Trinkets mod required for Alchemist is not currently available on Curseforge for version 1.21
The mod on first run downloaded a version of Trinkets that causes an instant crash before Minecraft load

"The game crashed whilst bootstrap
Error: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1303 failed"
[crash-2024-06-16_13.24.32-client.txt](https://github.com/user-attachments/files/15859438/crash-2024-06-16_13.24.32-client.txt)

**Comment by Zhaulus** [comment]
Trinkets mod downloaded appears to be for Fabric 1.20.6, not 1.21

**Comment by unix-supremacist** [comment]
for now use [polymer trinkets](https://modrinth.com/mod/trinkets-polymer), if you wanted to use the mod serverside only, you want the polymer version anyway, i just marked regular trinkets on curseforge as polymer trinkets is not on there, this should be fixed as soon as trinkets uploads their 1.21 build.

**Comment by Zhaulus** [comment]
Thanks will test

**Comment by Zhaulus** [comment]
No crashes yet, thanks

**Comment by unix-supremacist** [comment]
cool closing issue, if anything else happens let me know
